volumes:
  pg_data:
  static:
  media:

services:

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: seatle188/kittygram_backend:latest
    env_file:
      - .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres

  frontend:
    image: seatle188/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: seatle188/kittygram_gateway:latest
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend